#!/bin/env bash

focusedMonitor="$(hyprctl monitors all | grep -P 'focused: yes|Monitor' | grep -B1 'focused: yes' | sed '2,2d' | awk '{ print $2 }')"
cd $(dirname $0)

pidof keyboardMouse || sudo WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR keyboardMouseRootDir=$PWD ./keyboardMouse "$focusedMonitor" $@
